name: Bug report
description: Report something that's broken
labels: ['bug']
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - '@jk2908/cxx'
        - 'vscode-cxx'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: 'OS, Node, bundler, React, VS Code versions'
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell